.PHONY: build
build: clean
	./scripts/build.sh

.PHONY: clean
clean:
	./scripts/clean.sh

.PHONY: test
test:
	./scripts/test.sh

.PHONY: test-one
test-one:
	./scripts/test-one.sh

.PHONY: copy
copy:
	./scripts/copy.sh
